[package]
name = "palletizer"
description = "self-hosted Cargo registry"
version = "0.0.0"
authors = ["Maarten de Vries <maarten@de-vri.es>"]
license = "BSD-2-Clause"
edition = "2018"

[dependencies]
git2 = "0.13.12"
serde = { version = "1.0.117", features = ["derive"] }
toml = "0.5.7"
serde_json = "1.0.59"
thiserror = "1.0.22"

[workspace]
members = ["tools"]
