name: tests
on:
  push: { branches: ["main"] }
  pull_request: { branches: "*" }

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Build
        run: cargo build --workspace --all-targets --all-features --color=always
      - name: Clippy
        uses: auguwu/clippy-action@1.5.0
        with:
          token: ${{secrets.GITHUB_TOKEN}}
      - name: Test
        run: cargo test --workspace --all-targets --all-features --color=always
